-- BantayLink provenance database
-- PostgreSQL-compatible. IDs are generated by the application, not the database.

CREATE TABLE IF NOT EXISTS sources (
  id TEXT PRIMARY KEY,
  source_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  source_class TEXT NOT NULL,
  publisher TEXT,
  canonical_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingestion_runs (
  id TEXT PRIMARY KEY,
  adapter_id TEXT NOT NULL,
  source_id TEXT REFERENCES sources(id),
  source_version TEXT,
  source_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed')),
  records_seen INTEGER NOT NULL DEFAULT 0,
  records_inserted INTEGER NOT NULL DEFAULT 0,
  records_updated INTEGER NOT NULL DEFAULT 0,
  records_skipped INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS raw_documents (
  id TEXT PRIMARY KEY,
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  source_id TEXT NOT NULL REFERENCES sources(id),
  canonical_url TEXT,
  retrieval_url TEXT,
  request_method TEXT NOT NULL DEFAULT 'GET',
  response_headers JSONB NOT NULL DEFAULT '{}'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  http_status INTEGER,
  mime_type TEXT,
  payload_encoding TEXT NOT NULL DEFAULT 'jsonb',
  hash_algorithm TEXT NOT NULL DEFAULT 'sha256',
  hash_scope TEXT NOT NULL DEFAULT 'canonical_payload'
    CHECK (hash_scope IN ('raw_content','canonical_payload')),
  content_hash TEXT NOT NULL,
  payload JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_raw_documents_hash
  ON raw_documents(content_hash);

CREATE INDEX IF NOT EXISTS idx_raw_documents_source_time
  ON raw_documents(source_id, retrieved_at DESC);

ALTER TABLE ingestion_runs
  ADD COLUMN IF NOT EXISTS source_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS retrieval_url TEXT;

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS request_method TEXT NOT NULL DEFAULT 'GET';

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS response_headers JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS payload_encoding TEXT NOT NULL DEFAULT 'jsonb';

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS hash_algorithm TEXT NOT NULL DEFAULT 'sha256';

ALTER TABLE raw_documents
  ADD COLUMN IF NOT EXISTS hash_scope TEXT NOT NULL DEFAULT 'canonical_payload';

CREATE TABLE IF NOT EXISTS entities (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  canonical_key TEXT NOT NULL,
  label TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_type, canonical_key)
);

CREATE TABLE IF NOT EXISTS observations (
  id TEXT PRIMARY KEY,
  entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  source_id TEXT NOT NULL REFERENCES sources(id),
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  raw_document_id TEXT REFERENCES raw_documents(id),
  record_type TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content_hash TEXT NOT NULL,
  data JSONB NOT NULL,
  UNIQUE(source_id, source_record_id, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_observations_entity
  ON observations(entity_id);

CREATE INDEX IF NOT EXISTS idx_observations_source
  ON observations(source_id);

CREATE INDEX IF NOT EXISTS idx_observations_hash
  ON observations(content_hash);

CREATE TABLE IF NOT EXISTS observation_occurrences (
  observation_id TEXT NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE RESTRICT,
  raw_document_id TEXT NOT NULL REFERENCES raw_documents(id) ON DELETE RESTRICT,
  seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (observation_id, ingestion_run_id, raw_document_id)
);

CREATE INDEX IF NOT EXISTS idx_observation_occurrences_run
  ON observation_occurrences(ingestion_run_id);

CREATE INDEX IF NOT EXISTS idx_observation_occurrences_raw
  ON observation_occurrences(raw_document_id);

CREATE TABLE IF NOT EXISTS edges (
  id TEXT PRIMARY KEY,
  from_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  to_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  edge_type TEXT NOT NULL,
  source_id TEXT NOT NULL REFERENCES sources(id),
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  raw_document_id TEXT REFERENCES raw_documents(id),
  source_record_id TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content_hash TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(source_id, source_record_id, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_edges_from
  ON edges(from_entity_id);

CREATE INDEX IF NOT EXISTS idx_edges_to
  ON edges(to_entity_id);

CREATE INDEX IF NOT EXISTS idx_edges_type
  ON edges(edge_type);

CREATE TABLE IF NOT EXISTS edge_occurrences (
  edge_id TEXT NOT NULL REFERENCES edges(id) ON DELETE CASCADE,
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE RESTRICT,
  raw_document_id TEXT NOT NULL REFERENCES raw_documents(id) ON DELETE RESTRICT,
  seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (edge_id, ingestion_run_id, raw_document_id)
);

CREATE INDEX IF NOT EXISTS idx_edge_occurrences_run
  ON edge_occurrences(ingestion_run_id);

CREATE INDEX IF NOT EXISTS idx_edge_occurrences_raw
  ON edge_occurrences(raw_document_id);

-- Backfill repeat-run provenance for records already ingested before occurrence
-- tables existed. Future runs record each observation/edge occurrence explicitly.
INSERT INTO observation_occurrences (observation_id, ingestion_run_id, raw_document_id, seen_at)
SELECT id, ingestion_run_id, raw_document_id, observed_at
FROM observations
WHERE raw_document_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO edge_occurrences (edge_id, ingestion_run_id, raw_document_id, seen_at)
SELECT id, ingestion_run_id, raw_document_id, observed_at
FROM edges
WHERE raw_document_id IS NOT NULL
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION bantaylink_prevent_provenance_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'BantayLink provenance table % is append-only; % is not permitted',
    TG_TABLE_NAME, TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS raw_documents_append_only ON raw_documents;
CREATE TRIGGER raw_documents_append_only
BEFORE UPDATE OR DELETE ON raw_documents
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_provenance_mutation();

DROP TRIGGER IF EXISTS observations_append_only ON observations;
CREATE TRIGGER observations_append_only
BEFORE UPDATE OR DELETE ON observations
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_provenance_mutation();

DROP TRIGGER IF EXISTS edges_append_only ON edges;
CREATE TRIGGER edges_append_only
BEFORE UPDATE OR DELETE ON edges
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_provenance_mutation();

DROP TRIGGER IF EXISTS observation_occurrences_append_only ON observation_occurrences;
CREATE TRIGGER observation_occurrences_append_only
BEFORE UPDATE OR DELETE ON observation_occurrences
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_provenance_mutation();

DROP TRIGGER IF EXISTS edge_occurrences_append_only ON edge_occurrences;
CREATE TRIGGER edge_occurrences_append_only
BEFORE UPDATE OR DELETE ON edge_occurrences
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_provenance_mutation();

CREATE TABLE IF NOT EXISTS correlation_runs (
  id TEXT PRIMARY KEY,
  engine_version TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  entity_count INTEGER NOT NULL DEFAULT 0,
  observation_count INTEGER NOT NULL DEFAULT 0,
  edge_count INTEGER NOT NULL DEFAULT 0,
  finding_count INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS correlation_findings (
  id TEXT PRIMARY KEY,
  correlation_run_id TEXT NOT NULL REFERENCES correlation_runs(id) ON DELETE CASCADE,
  rule_id TEXT NOT NULL,
  finding_type TEXT NOT NULL,
  status TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  subject_entity_id TEXT REFERENCES entities(id) ON DELETE SET NULL,
  related_entity_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_observation_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_edge_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(correlation_run_id, fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_run
  ON correlation_findings(correlation_run_id);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_rule
  ON correlation_findings(rule_id);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_subject
  ON correlation_findings(subject_entity_id);


CREATE TABLE IF NOT EXISTS entity_resolution_runs (
  id TEXT PRIMARY KEY,
  engine_version TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  entity_count INTEGER NOT NULL DEFAULT 0,
  candidate_count INTEGER NOT NULL DEFAULT 0,
  auto_confirmed_count INTEGER NOT NULL DEFAULT 0,
  review_required_count INTEGER NOT NULL DEFAULT 0,
  conflict_count INTEGER NOT NULL DEFAULT 0,
  cluster_count INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb
);


CREATE INDEX IF NOT EXISTS idx_entity_resolution_runs_status
  ON entity_resolution_runs(status, completed_at DESC);

ALTER TABLE entity_resolution_runs
  ADD COLUMN IF NOT EXISTS cluster_count INTEGER NOT NULL DEFAULT 0;


CREATE TABLE IF NOT EXISTS entity_resolution_candidates (
  id TEXT PRIMARY KEY,
  entity_resolution_run_id TEXT NOT NULL REFERENCES entity_resolution_runs(id) ON DELETE CASCADE,
  source_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  candidate_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  match_method TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('AUTO_CONFIRMED','REVIEW_REQUIRED','CONFLICT','REJECTED')),
  fingerprint TEXT NOT NULL,
  rationale TEXT NOT NULL,
  evidence_observation_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_edge_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_resolution_run_id, fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_candidates_run
  ON entity_resolution_candidates(entity_resolution_run_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_candidates_source
  ON entity_resolution_candidates(source_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_candidates_candidate
  ON entity_resolution_candidates(candidate_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_candidates_status
  ON entity_resolution_candidates(status);

ALTER TABLE entity_resolution_candidates
  DROP CONSTRAINT IF EXISTS entity_resolution_candidates_source_entity_id_fkey,
  DROP CONSTRAINT IF EXISTS entity_resolution_candidates_candidate_entity_id_fkey;

ALTER TABLE entity_resolution_candidates
  ADD CONSTRAINT entity_resolution_candidates_source_entity_id_fkey
    FOREIGN KEY (source_entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
  ADD CONSTRAINT entity_resolution_candidates_candidate_entity_id_fkey
    FOREIGN KEY (candidate_entity_id) REFERENCES entities(id) ON DELETE RESTRICT;



CREATE TABLE IF NOT EXISTS entity_resolution_assertions (
  id TEXT PRIMARY KEY,
  source_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  canonical_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  assertion_type TEXT NOT NULL CHECK (assertion_type IN ('AUTO_CONFIRMED','HUMAN_CONFIRMED','HUMAN_REJECTED')),
  resolution_run_id TEXT REFERENCES entity_resolution_runs(id),
  evidence_observation_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_edge_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  basis JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_assertions_source
  ON entity_resolution_assertions(source_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_assertions_canonical
  ON entity_resolution_assertions(canonical_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_assertions_type
  ON entity_resolution_assertions(assertion_type);

ALTER TABLE entity_resolution_assertions
  DROP CONSTRAINT IF EXISTS entity_resolution_assertions_source_entity_id_fkey,
  DROP CONSTRAINT IF EXISTS entity_resolution_assertions_canonical_entity_id_fkey;

ALTER TABLE entity_resolution_assertions
  ADD CONSTRAINT entity_resolution_assertions_source_entity_id_fkey
    FOREIGN KEY (source_entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
  ADD CONSTRAINT entity_resolution_assertions_canonical_entity_id_fkey
    FOREIGN KEY (canonical_entity_id) REFERENCES entities(id) ON DELETE RESTRICT;



CREATE TABLE IF NOT EXISTS entity_resolution_clusters (
  id TEXT PRIMARY KEY,
  entity_resolution_run_id TEXT NOT NULL REFERENCES entity_resolution_runs(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL,
  cluster_key TEXT NOT NULL,
  representative_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE RESTRICT,
  member_entity_ids TEXT[] NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('AUTO_CONFIRMED','REVIEW_REQUIRED')),
  basis JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_resolution_run_id, cluster_key)
);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_clusters_run
  ON entity_resolution_clusters(entity_resolution_run_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_clusters_representative
  ON entity_resolution_clusters(representative_entity_id);

CREATE INDEX IF NOT EXISTS idx_entity_resolution_clusters_type
  ON entity_resolution_clusters(entity_type);



CREATE OR REPLACE FUNCTION bantaylink_prevent_resolution_assertion_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'BantayLink resolution assertions are append-only; % is not permitted', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS entity_resolution_assertions_append_only ON entity_resolution_assertions;
CREATE TRIGGER entity_resolution_assertions_append_only
BEFORE UPDATE OR DELETE ON entity_resolution_assertions
FOR EACH ROW EXECUTE FUNCTION bantaylink_prevent_resolution_assertion_mutation();

