-- BantayLink provenance database
-- PostgreSQL-compatible. IDs are generated by the application, not the database.

CREATE TABLE IF NOT EXISTS sources (
  id TEXT PRIMARY KEY,
  source_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  source_class TEXT NOT NULL,
  publisher TEXT,
  canonical_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ingestion_runs (
  id TEXT PRIMARY KEY,
  adapter_id TEXT NOT NULL,
  source_id TEXT REFERENCES sources(id),
  source_version TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed')),
  records_seen INTEGER NOT NULL DEFAULT 0,
  records_inserted INTEGER NOT NULL DEFAULT 0,
  records_updated INTEGER NOT NULL DEFAULT 0,
  records_skipped INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS raw_documents (
  id TEXT PRIMARY KEY,
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  source_id TEXT NOT NULL REFERENCES sources(id),
  canonical_url TEXT,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  http_status INTEGER,
  mime_type TEXT,
  content_hash TEXT NOT NULL,
  payload JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_raw_documents_hash
  ON raw_documents(content_hash);

CREATE TABLE IF NOT EXISTS entities (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  canonical_key TEXT NOT NULL,
  label TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_type, canonical_key)
);

CREATE TABLE IF NOT EXISTS observations (
  id TEXT PRIMARY KEY,
  entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  source_id TEXT NOT NULL REFERENCES sources(id),
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  raw_document_id TEXT REFERENCES raw_documents(id),
  record_type TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content_hash TEXT NOT NULL,
  data JSONB NOT NULL,
  UNIQUE(source_id, source_record_id, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_observations_entity
  ON observations(entity_id);

CREATE INDEX IF NOT EXISTS idx_observations_source
  ON observations(source_id);

CREATE INDEX IF NOT EXISTS idx_observations_hash
  ON observations(content_hash);

CREATE TABLE IF NOT EXISTS edges (
  id TEXT PRIMARY KEY,
  from_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  to_entity_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  edge_type TEXT NOT NULL,
  source_id TEXT NOT NULL REFERENCES sources(id),
  ingestion_run_id TEXT NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  raw_document_id TEXT REFERENCES raw_documents(id),
  source_record_id TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content_hash TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(source_id, source_record_id, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_edges_from
  ON edges(from_entity_id);

CREATE INDEX IF NOT EXISTS idx_edges_to
  ON edges(to_entity_id);

CREATE INDEX IF NOT EXISTS idx_edges_type
  ON edges(edge_type);


CREATE TABLE IF NOT EXISTS correlation_runs (
  id TEXT PRIMARY KEY,
  engine_version TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  entity_count INTEGER NOT NULL DEFAULT 0,
  observation_count INTEGER NOT NULL DEFAULT 0,
  edge_count INTEGER NOT NULL DEFAULT 0,
  finding_count INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS correlation_findings (
  id TEXT PRIMARY KEY,
  correlation_run_id TEXT NOT NULL REFERENCES correlation_runs(id) ON DELETE CASCADE,
  rule_id TEXT NOT NULL,
  finding_type TEXT NOT NULL,
  status TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  subject_entity_id TEXT REFERENCES entities(id) ON DELETE SET NULL,
  related_entity_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_observation_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  evidence_edge_ids TEXT[] NOT NULL DEFAULT '{}'::text[],
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(correlation_run_id, fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_run
  ON correlation_findings(correlation_run_id);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_rule
  ON correlation_findings(rule_id);

CREATE INDEX IF NOT EXISTS idx_correlation_findings_subject
  ON correlation_findings(subject_entity_id);
